# Permalinks
permalink:           pretty

# Setup
title:               Terry Prokop
tagline:             Journey into Data Science blog
url:                 https://toko258.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Terry Prokop
  url:               https://toko258.github.io
  email:             tpro713@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/toko258

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-theme-lanyon
# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
